server:
  port: 8031
  servlet:
    context-path: /bff-service

spring:
  main:
    allow-bean-definition-overriding: true

springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256

log:
  path: /Users/usuario/desarrollo/logsBorrar